language: generic
sudo: required
services:
  - docker

before_install:
  - docker-compose -f docker-compose-dev.yml up
  - docker-compose -f docker-compose-dev.yml up --build
  - docker-compose -f docker-compose-dev.yml down

script:
  - docker run -e CI=true edwinisnow/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-west-2-322441192339"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
